{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/svd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svd/svd_{{ version }}.tar.gz
  sha256: 0f586e7fd00487ef4a8408e4dc907f6fcb3a8b4624b1cd6c3beaab203755e067

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('svd')"           # [not win]
    - "\"%R%\" -e \"library('svd')\""  # [win]

about:
  home: http://github.com/asl/svd
  license: BSD-3-Clause
  summary: R bindings to SVD and eigensolvers (PROPACK, nuTRLan).
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: svd
# Type: Package
# Imports: methods
# Suggests: testthat (>= 0.7)
# Title: Interfaces to Various State-of-Art SVD and Eigensolvers
# Version: 0.5
# Author: Anton Korobeynikov [aut, cre], Rasmus Munk Larsen [ctb, cph], Lawrence Berkeley National Laboratory [ctb, cph]
# Maintainer: Anton Korobeynikov <anton@korobeynikov.info>
# Description: R bindings to SVD and eigensolvers (PROPACK, nuTRLan).
# License: BSD_3_clause + file LICENSE
# Copyright: see file COPYRIGHTS
# URL: http://github.com/asl/svd
# NeedsCompilation: yes
# Packaged: 2019-08-19 09:13:26 UTC; asl
# Repository: CRAN
# Date/Publication: 2019-08-19 11:20:05 UTC
