{% set version = "0.4.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svd
  version: {{ version|replace("-", "_") }}

source:
  fn: svd_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/svd_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/svd/svd_{{ version }}.tar.gz

  sha256: c467f6ad914efc75de7e6eb8c2af12cce5ee32bc1e8e43ca36cf3a3315fe9b72

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('svd')"  # [not win]
    - "\"%R%\" -e \"library('svd')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/svd/index.html
  license: BSD_3_clause
  summary: R bindings to SVD and eigensolvers (PROPACK, nuTRLan).
  license_family: BSD
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
