{% set version = "0.5.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-svd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/svd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svd/svd_{{ version }}.tar.gz
  sha256: 50994e78708ddbebf7ba937846e2cadde48437a6e26f1af0a9cfbfd624441514

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base

test:
  commands:
    - $R -e "library('svd')"           # [not win]
    - "\"%R%\" -e \"library('svd')\""  # [win]

about:
  home: http://github.com/asl/svd
  license: BSD-3-Clause
  summary: R bindings to SVD and eigensolvers (PROPACK, nuTRLan).
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
