appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rhmBjOfxdev9IlBmcbHtaxWI5MxaC5lp6dW657gRnXCeDx29zKWTjKppW3x2qy3/UduZKh1jat0hACuItaDzzyKBZek181TxXu5XrLhdyiL1j35v6ItO+881mmQ4EES3QIj4zt+eeX3NdFLoPY/RbE9n6kq9CKrZZdUBHcGuMvp1TUJfnEGkM0nFJr6ujBiI+zd5DsNuNhjKbLXGMXyCvBPma86lV4Haaz9odQDbSRv7JOjdm0WDULpc1ItPG/GVigG5FxB540G6mlSzELyconw1y78qQgy47Bi1VoLSY/F7cIWkdDndWOQGloT3XLz1p1IFVzOJ/wgWDs3aTVAF/T88Yi5HEbyHllG1MM60AqCJcXw9r8rpPJqNjPwB6qzVegTzzS9OS6ggKrqKUeAxWx+rIzQWdRWJ6C/UUCDdmo/ZAloaRjaynj98Jr4oHDTf5hwKuT/7CcMk0SqBbicOYbrJr+4FVI3pmIIgqD/oez9jI6JHeNK0G3yxQUxksgWZTfrP33kHGphNMd+zBkcy3fRtGIEyoVhFTIgn7BMQAzPjuxdttUn9Q0VJ7trQFKZPfrJu+w10P/cXXfotYL/hKuUVtx7QVFDwjlXCiLMc8jh8346Vg3nGmuGzyK0Bo/RZUh3tm1MIJF6AxNEnECyeGLdueCDL9NTEztBItVRS2EE=}
